ktor:
    databaseUrl: "$DATABASE_URL:"
    SECRET_JWT: "$SECRET_JWT:"
    infoFetch:
        initialDelayHours: 1
        intervalHours: 6
    application:
        modules:
            - com.ghn.ApplicationKt.module
    deployment:
        port: 8080
